name: Build Kernel (ALL)
on:
  push:
    branches: [master test]
  pull_request:
    branches: [master test]
  workflow_dispatch:
    inputs:
      any:
        description: 'Any'
        required: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: 'checkout'
        submodules: 'recursive'
    - name: Run Build Script
      id: build
      run: |
        pushd checkout
        ./usb_cam.sh
        echo "::set-output name=release_path::$(pwd)/build"
        echo "::set-output name=release_files::$(pwd)/build/vmlinux"
        popd
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: kernel-image
        path: ${{ steps.build.outputs.release_path }}
    - name: Generate Release Tag
      id: tag
      run: |
        # https://github.com/softprops/action-gh-release/issues/20
        echo "::set-output name=release_tag::nightly_$(date +'%Y.%m.%d_%H.%M')"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: ${{ steps.build.outputs.release_files }}
